### PR TITLE
Fix indentation issues

### LINKED ISSUE #72: Indentation of objects inside an array
json-mode does not indent objects inside an array properly.

Actual:
```json
[
    {
    "key": "value"
}
]
```

Expected:
```json
[
    {
        "key": "value"
    }
]
```

### PR DESCRIPTION
**Pull request by VlachJosef**
Fixes #72

### CODE REVIEW

**Comment by rsimoes** [comment]
Any hope of this getting merged?

**Comment by lshouzhong** [comment]
It seems that the author has forgotten that he has such a project. 😂😂😂

**Comment by taku0** [comment]
@joshwnj
Can I be a maintainer of this project?

I'm a maintainer of [`swift-mode`](https://github.com/swift-emacs/swift-mode) and the author of [JSON Par mode](https://github.com/taku0/json-par/), a minor mode for structural editing of JSON based on `json-mode`.  I will fix things like this PR while keeping `json-par` simple.

Cloud you [create a organization](https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/creating-a-new-organization-from-scratch), [transfer the repository to the organization](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository), and add me to the organization?  For example, `swift-mode` is managed under [`swift-emacs`](https://github.com/swift-emacs) organization.

**Comment by taku0** [comment]
I have confirmed that it works. Merging.

I became a `json-mode` maintainer just a few minutes ago. Thank you @joshwnj.

**Pull request merged**
